# Copyright (c) 2026, Bop Agency and Contributors
# See license.txt

class TransactionOrigin:
	WEB = "WEB"
	PHONE = "PHONE"
	COUNTER = "COUNTER"
	MANUAL = "MANUAL"
	API = "API"
	EDI = "EDI"
	MARKETPLACE = "MARKETPLACE"
	OTHER = "OTHER"

	ALL = (WEB, PHONE, COUNTER, MANUAL, API, EDI, MARKETPLACE, OTHER)

class ChannelType:
	PRESTASHOP = "PRESTASHOP"
	MARKETPLACE = "MARKETPLACE"
	PHONE = "PHONE"
	COUNTER = "COUNTER"
	INTERNAL = "INTERNAL"
	OTHER = "OTHER"

	ALL = (PRESTASHOP, MARKETPLACE, PHONE, COUNTER, INTERNAL, OTHER)

class IntegrationProvider:
	NONE = "NONE"
	PRESTASHOP = "PRESTASHOP"
	MARKETPLACE = "MARKETPLACE"
	EDI = "EDI"
	INTERNAL = "INTERNAL"
	OTHER = "OTHER"

	ALL = (NONE, PRESTASHOP, MARKETPLACE, EDI, INTERNAL, OTHER)

class ExternalEntityType:
	PRODUCT = "PRODUCT"
	PRODUCT_VARIANT = "PRODUCT_VARIANT"
	CATEGORY = "CATEGORY"
	CUSTOMER = "CUSTOMER"
	ADDRESS = "ADDRESS"
	ORDER = "ORDER"
	INVOICE = "INVOICE"
	PAYMENT = "PAYMENT"
	SHIPMENT = "SHIPMENT"
	INVENTORY = "INVENTORY"
	PRICE = "PRICE"
	WAREHOUSE = "WAREHOUSE"
	STOCK_LOCATION = "STOCK_LOCATION"
	REFUND = "REFUND"
	VENDOR = "VENDOR"

	ALL = (
		PRODUCT,
		PRODUCT_VARIANT,
		CATEGORY,
		CUSTOMER,
		ADDRESS,
		ORDER,
		INVOICE,
		PAYMENT,
		SHIPMENT,
		INVENTORY,
		PRICE,
		WAREHOUSE,
		STOCK_LOCATION,
		REFUND,
		VENDOR,
	)

class IntegrationDirection:
	INBOUND = "INBOUND"
	OUTBOUND = "OUTBOUND"

	ALL = (INBOUND, OUTBOUND)

class IntegrationOperation:
	CREATE = "CREATE"
	UPDATE = "UPDATE"
	DELETE = "DELETE"
	UPSERT = "UPSERT"
	SYNC = "SYNC"
	WEBHOOK = "WEBHOOK"
	INGEST_ORDER = "INGEST_ORDER"
	RECONCILE_ORDER_STATE = "RECONCILE_ORDER_STATE"
	UPDATE_ORDER_FULFILLMENT_STATE = "UPDATE_ORDER_FULFILLMENT_STATE"

	ALL = (
		CREATE,
		UPDATE,
		DELETE,
		UPSERT,
		SYNC,
		WEBHOOK,
		INGEST_ORDER,
		RECONCILE_ORDER_STATE,
		UPDATE_ORDER_FULFILLMENT_STATE,
	)

class IntegrationStatus:
	RECEIVED = "RECEIVED"
	PENDING = "PENDING"
	PROCESSING = "PROCESSING"
	SUCCEEDED = "SUCCEEDED"
	FAILED = "FAILED"
	RETRY_PENDING = "RETRY_PENDING"
	DEAD_LETTER = "DEAD_LETTER"
	CANCELLED = "CANCELLED"

	ALL = (
		RECEIVED,
		PENDING,
		PROCESSING,
		SUCCEEDED,
		FAILED,
		RETRY_PENDING,
		DEAD_LETTER,
		CANCELLED,
	)

	TERMINAL = (SUCCEEDED, DEAD_LETTER, CANCELLED)

class ErrorCategory:
	TRANSIENT = "TRANSIENT"
	RATE_LIMIT = "RATE_LIMIT"
	AUTHENTICATION = "AUTHENTICATION"
	VALIDATION = "VALIDATION"
	NOT_FOUND = "NOT_FOUND"
	CONFLICT = "CONFLICT"
	PROVIDER_ERROR = "PROVIDER_ERROR"
	INTERNAL_ERROR = "INTERNAL_ERROR"
	NON_RETRYABLE = "NON_RETRYABLE"

	ALL = (
		TRANSIENT,
		RATE_LIMIT,
		AUTHENTICATION,
		VALIDATION,
		NOT_FOUND,
		CONFLICT,
		PROVIDER_ERROR,
		INTERNAL_ERROR,
		NON_RETRYABLE,
	)

	RETRYABLE = (TRANSIENT, RATE_LIMIT, PROVIDER_ERROR, INTERNAL_ERROR)
	NON_RETRYABLE_SET = (AUTHENTICATION, VALIDATION, NOT_FOUND, NON_RETRYABLE)

class IntegrationReadinessStatus:
	INGESTION_PENDING = "INGESTION_PENDING"
	RESERVATION_PENDING = "RESERVATION_PENDING"
	READY = "READY"
	FAILED_REVIEW = "FAILED_REVIEW"
	CANCELLATION_PENDING = "CANCELLATION_PENDING"
	CANCELLED = "CANCELLED"
	CHANGE_REVIEW_REQUIRED = "CHANGE_REVIEW_REQUIRED"

	ALL = (
		INGESTION_PENDING,
		RESERVATION_PENDING,
		READY,
		FAILED_REVIEW,
		CANCELLATION_PENDING,
		CANCELLED,
		CHANGE_REVIEW_REQUIRED,
	)

class ExternalOrderStateAction:
	ACTIVE = "ACTIVE"
	CANCEL_BEFORE_FULFILLMENT = "CANCEL_BEFORE_FULFILLMENT"
	REVIEW_REQUIRED = "REVIEW_REQUIRED"
	IGNORE = "IGNORE"

	ALL = (
		ACTIVE,
		CANCEL_BEFORE_FULFILLMENT,
		REVIEW_REQUIRED,
		IGNORE,
	)

class PickTicketStatus:
	DRAFT = "DRAFT"
	READY_TO_PICK = "READY_TO_PICK"
	PICKING = "PICKING"
	PICKED = "PICKED"
	CANCELLED = "CANCELLED"

	ALL = (
		DRAFT,
		READY_TO_PICK,
		PICKING,
		PICKED,
		CANCELLED,
	)

class ShippingTicketStatus:
	DRAFT = "DRAFT"
	READY_TO_SHIP = "READY_TO_SHIP"
	SHIPPED = "SHIPPED"
	CANCELLED = "CANCELLED"

	ALL = (
		DRAFT,
		READY_TO_SHIP,
		SHIPPED,
		CANCELLED,
	)
