# Copyright (c) 2026, Bop Agency and Contributors
# See license.txt

class TransactionOrigin:
	WEB = "WEB"
	PHONE = "PHONE"
	COUNTER = "COUNTER"
	MANUAL = "MANUAL"
	API = "API"
	EDI = "EDI"
	MARKETPLACE = "MARKETPLACE"
	OTHER = "OTHER"

	ALL = (WEB, PHONE, COUNTER, MANUAL, API, EDI, MARKETPLACE, OTHER)

class ChannelType:
	PRESTASHOP = "PRESTASHOP"
	MARKETPLACE = "MARKETPLACE"
	PHONE = "PHONE"
	COUNTER = "COUNTER"
	INTERNAL = "INTERNAL"
	OTHER = "OTHER"

	ALL = (PRESTASHOP, MARKETPLACE, PHONE, COUNTER, INTERNAL, OTHER)

class IntegrationProvider:
	NONE = "NONE"
	PRESTASHOP = "PRESTASHOP"
	OTHER = "OTHER"

	ALL = (NONE, PRESTASHOP, OTHER)

class ExternalEntityType:
	PRODUCT = "PRODUCT"
	PRODUCT_VARIANT = "PRODUCT_VARIANT"
	CATEGORY = "CATEGORY"
	CUSTOMER = "CUSTOMER"
	ADDRESS = "ADDRESS"
	ORDER = "ORDER"
	INVOICE = "INVOICE"
	PAYMENT = "PAYMENT"
	SHIPMENT = "SHIPMENT"

	ALL = (
		PRODUCT,
		PRODUCT_VARIANT,
		CATEGORY,
		CUSTOMER,
		ADDRESS,
		ORDER,
		INVOICE,
		PAYMENT,
		SHIPMENT,
	)
